#!/usr/bin/env python3
"""Generate claude/{skills,agents}/INDEX.md catalogues.

Deterministic: no clocks, shells, env reads, or mtime. Re-runs are byte-
identical. Sort case-sensitive by name. Frontmatter must start the file
(after at most one HTML comment); files lacking ``description:`` are
skipped with stderr warnings. Pipe ``|`` escaped to ``\\|``; block-scalar
descriptions collect first content line only. ``INDEX.md`` self-skipped.
"""
from __future__ import annotations
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FOOTER = ("\n## Generation\n\nThis file is auto-generated by "
          "`python3 scripts/build_skills_index.py`. "
          "Do not edit by hand — re-run the script.\n")

def parse_desc(path):
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return None
    i, n = 0, len(lines)
    while i < n and not lines[i].strip():
        i += 1
    if i < n and lines[i].lstrip().startswith("<!--"):
        while i < n and "-->" not in lines[i]:
            i += 1
        i += 1
        while i < n and not lines[i].strip():
            i += 1
    if i >= n or lines[i].rstrip() != "---":
        return None
    end = next((j for j in range(i + 1, n) if lines[j].rstrip() == "---"), None)
    if end is None:
        return None
    block = lines[i + 1 : end]
    for k, ln in enumerate(block):
        m = re.match(r"^description:\s*(.*)$", ln)
        if not m:
            continue
        v = m.group(1).strip()
        if v in ("|", ">"):
            v = next((x.strip() for x in block[k + 1:] if x.strip()), "")
        if len(v) >= 2 and v[0] == v[-1] and v[0] in ('"', "'"):
            v = v[1:-1]
        return v or None
    return None

def emit(rows, col, out):
    parts = [f"| {col} | Description |\n", "|---|---|\n"]
    for name, desc in rows:
        cell = desc.replace("|", "\\|").replace("\n", " ").strip()
        parts.append(f"| `{name}` | {cell} |\n")
    parts.append(FOOTER)
    out.write_text("".join(parts), encoding="utf-8")

def collect(paths, key):
    rows = []
    for p in sorted(paths):
        d = parse_desc(p)
        if d is None:
            sys.stderr.write(f"SKIP {p.relative_to(ROOT)} (no parseable description)\n")
            continue
        rows.append((key(p), d))
    return rows

def main():
    sd, ad = ROOT / "claude" / "skills", ROOT / "claude" / "agents"
    skills = [d / "SKILL.md" for d in sd.iterdir()
              if d.is_dir() and (d / "SKILL.md").is_file()]
    agents = [f for f in ad.glob("*.md") if f.is_file() and f.name != "INDEX.md"]
    emit(collect(skills, lambda p: p.parent.name), "Skill", sd / "INDEX.md")
    emit(collect(agents, lambda p: p.stem), "Agent", ad / "INDEX.md")
    return 0

if __name__ == "__main__":
    sys.exit(main())
